apiVersion: apps/v1
kind: Deployment
metadata:
  name: universidad-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: universidad
  template:
    metadata:
      labels:
        app: universidad
    spec:
      containers:
      - name: app
        image: tuusuario/universidad-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://universidad-db:5432/universidades
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: postgres
